### ISSUE TITLE
Reorg & reboot the website

### ISSUE THREAD

**Issue by vmbrasseur** [agstack/agstack-website#58]
The existing live agstack.org website hasn't been updated in quite a while. This is a problem. It makes the project look dead, which it isn't.

Thankfully, Mikela started a new jekyll site here based on the existing live WordPress site. We'll be able to build on that to develop a new site that the community can drive on its own by way of the Github repo.

## Audiences in order of expected traffic

* Merely curious
* Potential members
* Potential contributors
* Current contributors
* Current members

## Initial goals for this work

* Move control of website out of Linux Foundation & into community, removing one step that may be preventing keeping the site up to date
* Make it clear what AgStack does & why
* Make it easy to find membership information
* Make it easy to find contribution/community information
* Make it easy to find governance information

That’s more than enough for this pass on the site. Later the community can iterate on the site as needed.

## Task list

- [x] Fix footer
- [ ] ~~Fill out project pages~~ (already contain all the info we have, really)
- [x] Get projects page working
- [ ] Confirm contact form works
- [x] Add content to index.markdown
- [x] Change index hero image
- [ ] Add members to Membership page (requires #62 )
- [ ] Fill in Community page
- [x] Fill in Governance page
- [ ] Fill in Contribute page
- [x] Update About page

**Comment by vmbrasseur** [comment]
The existing jekyll website layout:

![agstack-jekyll-original-layout (1)](https://github.com/user-attachments/assets/741c35ef-6e3f-4753-af31-e2bceffd418d)

The new layout I'll be putting together:

![new-agstack-website drawio](https://github.com/user-attachments/assets/45fec1fb-5ec9-4dab-bc25-713aae4bc0c5)

I've run it past our web designer and he gave the layout a 👍 .

**Comment by vmbrasseur** [comment]
I've stubbed out the new pages and added them to the navbar. Next up…

1. Add basic content to each page
2. Make the blog work
3. Select/apply theme
4. Tweak until it all looks OK
5. Refine content
6. Launch!
